// <auto-generated />
using System;
using MagicShilla_Utility.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicCity_ShillaAPI.Migrations
{
    [DbContext(typeof(ShillaDbContext))]
    [Migration("20230916193224_identity-table-inserted")]
    partial class identitytableinserted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicShilla_Utility.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MagicShilla_Utility.Entity.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("MagicShilla_Utility.Entity.Shilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Shillas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Magna Duis Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1615),
                            Details = "P.O. Box 267, 2824 Est Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#f98d8b",
                            Occupancy = 755,
                            Rate = 1.0,
                            Sqft = 687,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Eu Placerat Foundation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1625),
                            Details = "4693 Lacinia Av.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#aa281d",
                            Occupancy = 451,
                            Rate = 4.0,
                            Sqft = 183,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "A Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1626),
                            Details = "Ap #708-6258 Libero. Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#185c75",
                            Occupancy = 417,
                            Rate = 4.0,
                            Sqft = 369,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Sem Pellentesque Consulting",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1627),
                            Details = "P.O. Box 943, 2673 Integer Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#5f8209",
                            Occupancy = 608,
                            Rate = 2.0,
                            Sqft = 47,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Maecenas Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1629),
                            Details = "933-1316 Aliquet, Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#d5c7fc",
                            Occupancy = 531,
                            Rate = 2.0,
                            Sqft = 728,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Turpis PC",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1630),
                            Details = "Ap #612-6043 Odio. Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#01845b",
                            Occupancy = 948,
                            Rate = 3.0,
                            Sqft = 966,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Sed Dui Consulting",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1632),
                            Details = "516-2918 Orci Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#ff180c",
                            Occupancy = 505,
                            Rate = 3.0,
                            Sqft = 54,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Rutrum Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1633),
                            Details = "Ap #278-793 Sapien, St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#4ee8c6",
                            Occupancy = 340,
                            Rate = 4.0,
                            Sqft = 591,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Lorem Luctus Ut Corp.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1635),
                            Details = "Ap #378-1639 Mollis Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#dabaf4",
                            Occupancy = 19,
                            Rate = 4.0,
                            Sqft = 727,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Id Erat Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1637),
                            Details = "Ap #425-1896 Orci, Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#67238c",
                            Occupancy = 432,
                            Rate = 3.0,
                            Sqft = 324,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Amenity = "Placerat Cras Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1638),
                            Details = "736-5324 Tellus Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#dd48ea",
                            Occupancy = 475,
                            Rate = 4.0,
                            Sqft = 714,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Amenity = "Turpis Consulting",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1640),
                            Details = "Ap #906-3587 Purus Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#5ce06d",
                            Occupancy = 18,
                            Rate = 2.0,
                            Sqft = 183,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Amenity = "Sed Libero Proin Consulting",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1641),
                            Details = "645-6096 Aliquet. Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#b3f9a7",
                            Occupancy = 173,
                            Rate = 3.0,
                            Sqft = 83,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Amenity = "In Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1642),
                            Details = "Ap #563-3481 Suspendisse St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#c1f72c",
                            Occupancy = 519,
                            Rate = 1.0,
                            Sqft = 864,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Amenity = "Orci Luctus Institute",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1643),
                            Details = "820-1075 Scelerisque Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#826ce2",
                            Occupancy = 867,
                            Rate = 2.0,
                            Sqft = 366,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Amenity = "Amet Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1644),
                            Details = "7374 Dui. Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#9deaea",
                            Occupancy = 460,
                            Rate = 2.0,
                            Sqft = 185,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Amenity = "Quisque Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1646),
                            Details = "P.O. Box 569, 4735 Lorem St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#97ea38",
                            Occupancy = 610,
                            Rate = 5.0,
                            Sqft = 26,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Amenity = "Ut Mi Corp.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1647),
                            Details = "P.O. Box 252, 2275 Etiam St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#6b90c4",
                            Occupancy = 173,
                            Rate = 4.0,
                            Sqft = 885,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Amenity = "Fringilla Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1648),
                            Details = "997-4033 Parturient St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#ef83bb",
                            Occupancy = 922,
                            Rate = 1.0,
                            Sqft = 120,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Amenity = "Magna Et Ipsum Foundation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1649),
                            Details = "P.O. Box 885, 6278 Condimentum. Avenue",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#962913",
                            Occupancy = 113,
                            Rate = 3.0,
                            Sqft = 237,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Amenity = "Lobortis Risus Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1651),
                            Details = "P.O. Box 506, 4230 Facilisis, St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#e5dc59",
                            Occupancy = 258,
                            Rate = 3.0,
                            Sqft = 7,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Amenity = "Integer Aliquam Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1652),
                            Details = "8483 Amet, Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#1c0575",
                            Occupancy = 344,
                            Rate = 3.0,
                            Sqft = 717,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Amenity = "Nulla Tincidunt Neque Company",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1654),
                            Details = "929-3803 Natoque Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#35f4eb",
                            Occupancy = 278,
                            Rate = 2.0,
                            Sqft = 818,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Amenity = "Rutrum Non Hendrerit LLC",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1655),
                            Details = "P.O. Box 374, 7965 Sagittis Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#e002dc",
                            Occupancy = 377,
                            Rate = 1.0,
                            Sqft = 731,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Amenity = "Montes Nascetur Ridiculus Associates",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1656),
                            Details = "3650 Sed Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#b5c130",
                            Occupancy = 447,
                            Rate = 4.0,
                            Sqft = 414,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Amenity = "At Velit Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1658),
                            Details = "P.O. Box 377, 7945 Bibendum St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#9ac0ed",
                            Occupancy = 997,
                            Rate = 3.0,
                            Sqft = 597,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Amenity = "Risus A Ultricies Foundation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1659),
                            Details = "8133 Quisque St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#4b5caf",
                            Occupancy = 650,
                            Rate = 3.0,
                            Sqft = 293,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Amenity = "Mauris Ltd",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1660),
                            Details = "Ap #649-7305 Magna Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#2f4db7",
                            Occupancy = 608,
                            Rate = 4.0,
                            Sqft = 255,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Amenity = "Ornare Fusce Incorporated",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1661),
                            Details = "Ap #154-1924 Odio Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#f2ccff",
                            Occupancy = 444,
                            Rate = 3.0,
                            Sqft = 975,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Amenity = "Adipiscing Company",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1662),
                            Details = "Ap #698-3320 Et Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#b59ae0",
                            Occupancy = 780,
                            Rate = 1.0,
                            Sqft = 600,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Amenity = "Donec Tincidunt Donec Institute",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1663),
                            Details = "6172 Quisque St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#4d0dad",
                            Occupancy = 830,
                            Rate = 3.0,
                            Sqft = 309,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Amenity = "Lobortis Quis Corp.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1667),
                            Details = "6502 Diam St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#739fce",
                            Occupancy = 72,
                            Rate = 4.0,
                            Sqft = 734,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Amenity = "Libero Morbi Accumsan Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1668),
                            Details = "344-9391 Morbi Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#b33edd",
                            Occupancy = 954,
                            Rate = 4.0,
                            Sqft = 382,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Amenity = "Aenean LLP",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1669),
                            Details = "808-1141 Magna. Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#6c43b2",
                            Occupancy = 405,
                            Rate = 3.0,
                            Sqft = 773,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Amenity = "Erat Nonummy Company",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1670),
                            Details = "P.O. Box 601, 2326 Egestas Av.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#1be2df",
                            Occupancy = 614,
                            Rate = 1.0,
                            Sqft = 683,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            Amenity = "Nunc Ullamcorper Institute",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1672),
                            Details = "Ap #142-6481 Risus. Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#ad2752",
                            Occupancy = 634,
                            Rate = 4.0,
                            Sqft = 598,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            Amenity = "Vivamus Nisi Foundation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1674),
                            Details = "540-5506 Nunc Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#6f70c6",
                            Occupancy = 275,
                            Rate = 3.0,
                            Sqft = 761,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            Amenity = "Bibendum Fermentum Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1675),
                            Details = "1942 Tempus St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#6f9bed",
                            Occupancy = 468,
                            Rate = 5.0,
                            Sqft = 948,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            Amenity = "Non Incorporated",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1676),
                            Details = "P.O. Box 268, 2785 Et, Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#001159",
                            Occupancy = 378,
                            Rate = 4.0,
                            Sqft = 535,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            Amenity = "Integer Sem Elit Inc.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1677),
                            Details = "P.O. Box 494, 9508 Eleifend Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#e86fab",
                            Occupancy = 520,
                            Rate = 2.0,
                            Sqft = 67,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            Amenity = "Mus Aenean Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1679),
                            Details = "P.O. Box 136, 3789 Non Avenue",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#b6d321",
                            Occupancy = 719,
                            Rate = 4.0,
                            Sqft = 344,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            Amenity = "Ac Ltd",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1680),
                            Details = "9223 Faucibus Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#f413cb",
                            Occupancy = 41,
                            Rate = 4.0,
                            Sqft = 740,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            Amenity = "Dis PC",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1681),
                            Details = "995-9146 Rhoncus. Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#a07ed3",
                            Occupancy = 461,
                            Rate = 4.0,
                            Sqft = 784,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            Amenity = "A Ultricies Adipiscing Institute",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1682),
                            Details = "Ap #921-755 Sed Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#e87da8",
                            Occupancy = 625,
                            Rate = 3.0,
                            Sqft = 883,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            Amenity = "Auctor Velit Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1684),
                            Details = "Ap #757-3626 Donec Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#fcd0b3",
                            Occupancy = 722,
                            Rate = 4.0,
                            Sqft = 170,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            Amenity = "Urna Convallis Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1685),
                            Details = "143-8337 Orci Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#76f7ea",
                            Occupancy = 902,
                            Rate = 4.0,
                            Sqft = 952,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            Amenity = "Lorem Inc.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1686),
                            Details = "Ap #884-6920 Odio Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#66d69c",
                            Occupancy = 23,
                            Rate = 4.0,
                            Sqft = 670,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            Amenity = "Risus Corp.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1687),
                            Details = "Ap #672-903 Sapien. Av.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#eaea0e",
                            Occupancy = 640,
                            Rate = 3.0,
                            Sqft = 332,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            Amenity = "Sed Inc.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1689),
                            Details = "240-6931 Arcu. Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#db6f9c",
                            Occupancy = 650,
                            Rate = 1.0,
                            Sqft = 286,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            Amenity = "Dolor Associates",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1719),
                            Details = "501-4919 Ante St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#f9cf45",
                            Occupancy = 198,
                            Rate = 2.0,
                            Sqft = 701,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            Amenity = "Lacus Quisque Company",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1721),
                            Details = "590-2101 Phasellus Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#26e0a8",
                            Occupancy = 274,
                            Rate = 5.0,
                            Sqft = 196,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            Amenity = "Nullam Company",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1722),
                            Details = "1566 Tortor Avenue",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#9589d3",
                            Occupancy = 340,
                            Rate = 4.0,
                            Sqft = 377,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            Amenity = "Blandit Viverra Donec LLP",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1724),
                            Details = "266-6782 Tristique Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#9d41e2",
                            Occupancy = 330,
                            Rate = 1.0,
                            Sqft = 672,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            Amenity = "Semper Rutrum Fusce LLP",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1725),
                            Details = "Ap #145-9213 Et Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#e5cb64",
                            Occupancy = 344,
                            Rate = 1.0,
                            Sqft = 518,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            Amenity = "Malesuada Malesuada Integer Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1726),
                            Details = "7000 Ultricies Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#89d14b",
                            Occupancy = 871,
                            Rate = 2.0,
                            Sqft = 642,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            Amenity = "In Hendrerit Associates",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1727),
                            Details = "4389 Turpis Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#f4ce42",
                            Occupancy = 264,
                            Rate = 4.0,
                            Sqft = 463,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            Amenity = "Sed Nunc Est Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1728),
                            Details = "621-1395 Semper St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#06a096",
                            Occupancy = 617,
                            Rate = 2.0,
                            Sqft = 349,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            Amenity = "In Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1730),
                            Details = "Ap #603-8858 Nec Avenue",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#e0f285",
                            Occupancy = 155,
                            Rate = 1.0,
                            Sqft = 626,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            Amenity = "Sed Id Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1731),
                            Details = "Ap #175-5527 Sem Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#e5dd00",
                            Occupancy = 108,
                            Rate = 3.0,
                            Sqft = 842,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            Amenity = "Augue Sed Corp.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1732),
                            Details = "735-4990 Dignissim Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#abf48d",
                            Occupancy = 178,
                            Rate = 2.0,
                            Sqft = 131,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            Amenity = "Tincidunt Vehicula LLP",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1733),
                            Details = "7155 Elit. St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#aef4a1",
                            Occupancy = 746,
                            Rate = 1.0,
                            Sqft = 154,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            Amenity = "Lorem Ipsum Associates",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1734),
                            Details = "8322 Ipsum Avenue",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#456b01",
                            Occupancy = 535,
                            Rate = 2.0,
                            Sqft = 161,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            Amenity = "Gravida Incorporated",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1737),
                            Details = "Ap #980-2275 Est, St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#c379e0",
                            Occupancy = 845,
                            Rate = 1.0,
                            Sqft = 433,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            Amenity = "Molestie Sodales Inc.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1738),
                            Details = "Ap #871-2940 Nascetur St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#e0477f",
                            Occupancy = 128,
                            Rate = 4.0,
                            Sqft = 960,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            Amenity = "In Dolor Corp.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1739),
                            Details = "4158 Blandit Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#f79c79",
                            Occupancy = 233,
                            Rate = 3.0,
                            Sqft = 830,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            Amenity = "Aliquam Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1742),
                            Details = "P.O. Box 409, 3141 Proin Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#ba90dd",
                            Occupancy = 584,
                            Rate = 3.0,
                            Sqft = 170,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            Amenity = "Eget Mollis Lectus Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1743),
                            Details = "P.O. Box 269, 2735 Lorem Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#ea7670",
                            Occupancy = 952,
                            Rate = 3.0,
                            Sqft = 296,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            Amenity = "Egestas LLP",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1744),
                            Details = "Ap #863-5298 Urna. St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#9fb4ea",
                            Occupancy = 418,
                            Rate = 3.0,
                            Sqft = 533,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            Amenity = "Dapibus Ligula Limited",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1745),
                            Details = "Ap #810-2434 Facilisis Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#f6c7fc",
                            Occupancy = 385,
                            Rate = 4.0,
                            Sqft = 148,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            Amenity = "Molestie Arcu Ltd",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1747),
                            Details = "Ap #893-8389 Congue St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#3aeae7",
                            Occupancy = 72,
                            Rate = 1.0,
                            Sqft = 105,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            Amenity = "Ligula Eu Enim Associates",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1748),
                            Details = "756-6990 Adipiscing St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#78bed3",
                            Occupancy = 439,
                            Rate = 4.0,
                            Sqft = 242,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            Amenity = "Integer Tincidunt Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1749),
                            Details = "855-7170 Urna, Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#687aed",
                            Occupancy = 376,
                            Rate = 3.0,
                            Sqft = 599,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            Amenity = "Sem Nulla Interdum Consulting",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1750),
                            Details = "Ap #661-896 Cras Avenue",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#1eed2c",
                            Occupancy = 585,
                            Rate = 1.0,
                            Sqft = 884,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            Amenity = "Tortor Company",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1752),
                            Details = "872-8100 A Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#bdafed",
                            Occupancy = 806,
                            Rate = 3.0,
                            Sqft = 504,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            Amenity = "Odio Sagittis Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1753),
                            Details = "Ap #993-935 Sit Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#8e82ff",
                            Occupancy = 786,
                            Rate = 2.0,
                            Sqft = 394,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            Amenity = "Scelerisque Foundation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1755),
                            Details = "9855 Diam St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#b619ea",
                            Occupancy = 520,
                            Rate = 5.0,
                            Sqft = 804,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            Amenity = "Quis Lectus Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1756),
                            Details = "Ap #419-4455 Malesuada Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#40dd4a",
                            Occupancy = 570,
                            Rate = 4.0,
                            Sqft = 267,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            Amenity = "Est Ac Associates",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1757),
                            Details = "Ap #336-3777 Nonummy St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#c15303",
                            Occupancy = 121,
                            Rate = 2.0,
                            Sqft = 332,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            Amenity = "Erat Semper LLP",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1758),
                            Details = "8762 Orci Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#afa4f2",
                            Occupancy = 560,
                            Rate = 5.0,
                            Sqft = 727,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            Amenity = "Ullamcorper Foundation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1760),
                            Details = "149-8936 Nonummy Av.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#86efde",
                            Occupancy = 608,
                            Rate = 3.0,
                            Sqft = 993,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            Amenity = "Est Ac Mattis Corp.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1761),
                            Details = "Ap #534-1107 Metus. Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#e2485a",
                            Occupancy = 482,
                            Rate = 3.0,
                            Sqft = 882,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            Amenity = "Vitae Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1762),
                            Details = "P.O. Box 720, 9003 Arcu Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#1be540",
                            Occupancy = 629,
                            Rate = 3.0,
                            Sqft = 570,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            Amenity = "Duis Ac Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1763),
                            Details = "Ap #211-3822 Adipiscing Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#94ecef",
                            Occupancy = 901,
                            Rate = 5.0,
                            Sqft = 894,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            Amenity = "Enim PC",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1764),
                            Details = "P.O. Box 404, 8586 Sollicitudin Avenue",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#4ed31d",
                            Occupancy = 700,
                            Rate = 2.0,
                            Sqft = 862,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            Amenity = "Dis Parturient Ltd",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1766),
                            Details = "Ap #892-3444 Metus. St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#60e0b7",
                            Occupancy = 71,
                            Rate = 2.0,
                            Sqft = 537,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            Amenity = "Dictum Inc.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1767),
                            Details = "Ap #183-4643 Interdum Street",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#025782",
                            Occupancy = 33,
                            Rate = 1.0,
                            Sqft = 878,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            Amenity = "Quis Pede PC",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1768),
                            Details = "8387 Imperdiet Avenue",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#71f7c1",
                            Occupancy = 48,
                            Rate = 3.0,
                            Sqft = 353,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            Amenity = "Vel Convallis LLC",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1769),
                            Details = "377-3871 Eleifend Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#9c51ff",
                            Occupancy = 193,
                            Rate = 4.0,
                            Sqft = 184,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            Amenity = "Nulla Dignissim Incorporated",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1771),
                            Details = "P.O. Box 186, 5950 Blandit. Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#54f996",
                            Occupancy = 598,
                            Rate = 5.0,
                            Sqft = 641,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            Amenity = "Enim Diam Ltd",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1772),
                            Details = "Ap #794-199 Interdum Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#d4a4fc",
                            Occupancy = 838,
                            Rate = 3.0,
                            Sqft = 313,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            Amenity = "Erat Nonummy Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1773),
                            Details = "805-9439 Neque Av.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#95eda8",
                            Occupancy = 107,
                            Rate = 1.0,
                            Sqft = 986,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            Amenity = "Lacus LLP",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1774),
                            Details = "8274 Turpis St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#77afdd",
                            Occupancy = 677,
                            Rate = 4.0,
                            Sqft = 258,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            Amenity = "Et Libero LLP",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1775),
                            Details = "Ap #127-3380 Nibh. Av.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#b1f49c",
                            Occupancy = 338,
                            Rate = 5.0,
                            Sqft = 107,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            Amenity = "Elit Pharetra Ut Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1777),
                            Details = "720-2914 Dolor Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#9b7bce",
                            Occupancy = 541,
                            Rate = 4.0,
                            Sqft = 13,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            Amenity = "Dis Parturient Industries",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1778),
                            Details = "754-1700 Mi St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#77f9d7",
                            Occupancy = 422,
                            Rate = 3.0,
                            Sqft = 782,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            Amenity = "Arcu Vestibulum LLC",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1779),
                            Details = "Ap #750-8981 Luctus. Road",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#ffc987",
                            Occupancy = 724,
                            Rate = 4.0,
                            Sqft = 917,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            Amenity = "Pellentesque Sed Dictum PC",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1780),
                            Details = "P.O. Box 870, 9372 Vulputate Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#140a6d",
                            Occupancy = 771,
                            Rate = 3.0,
                            Sqft = 587,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            Amenity = "Et Consulting",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1781),
                            Details = "P.O. Box 631, 6280 Habitant Ave",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#74c433",
                            Occupancy = 765,
                            Rate = 2.0,
                            Sqft = 924,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 99,
                            Amenity = "Phasellus In Felis Corporation",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1782),
                            Details = "P.O. Box 694, 8037 Nunc Rd.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#cdf7a0",
                            Occupancy = 854,
                            Rate = 4.0,
                            Sqft = 998,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 100,
                            Amenity = "Mauris Aliquam Corp.",
                            CreatedAt = new DateTime(2023, 9, 16, 22, 32, 24, 519, DateTimeKind.Local).AddTicks(1783),
                            Details = "Ap #225-1998 Purus St.",
                            ImageUrl = "https://fakeimg.pl/350x200/?text=World&font=lobster",
                            Name = "#098265",
                            Occupancy = 432,
                            Rate = 3.0,
                            Sqft = 654,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MagicShilla_Utility.Entity.ShillaNumber", b =>
                {
                    b.Property<int>("ShillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShillaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ShillaNo");

                    b.HasIndex("ShillaID");

                    b.ToTable("ShillaNumbers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MagicShilla_Utility.Entity.ShillaNumber", b =>
                {
                    b.HasOne("MagicShilla_Utility.Entity.Shilla", "Shilla")
                        .WithMany()
                        .HasForeignKey("ShillaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shilla");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MagicShilla_Utility.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MagicShilla_Utility.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicShilla_Utility.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MagicShilla_Utility.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
